# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_station.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 30, 221, 141))
        self.groupBox.setObjectName("groupBox")
        self.Connect_Button = QtWidgets.QPushButton(self.groupBox)
        self.Connect_Button.setGeometry(QtCore.QRect(10, 90, 201, 34))
        self.Connect_Button.setToolTip("")
        self.Connect_Button.setObjectName("Connect_Button")
        self.com_Port = QtWidgets.QComboBox(self.groupBox)
        self.com_Port.setGeometry(QtCore.QRect(110, 30, 99, 24))
        self.com_Port.setObjectName("com_Port")
        self.com_Baud = QtWidgets.QComboBox(self.groupBox)
        self.com_Baud.setGeometry(QtCore.QRect(110, 60, 99, 24))
        self.com_Baud.setObjectName("com_Baud")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 81, 18))
        self.label_2.setObjectName("label_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 200, 251, 311))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Find_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.Find_Button.setGeometry(QtCore.QRect(20, 30, 201, 34))
        self.Find_Button.setObjectName("Find_Button")
        self.Move_Button = QtWidgets.QPushButton(self.groupBox_2)
        self.Move_Button.setGeometry(QtCore.QRect(20, 250, 201, 34))
        self.Move_Button.setObjectName("Move_Button")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 210, 201, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_4.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_4.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_4.addWidget(self.lineEdit_8)
        self.input_point = QtWidgets.QPushButton(self.groupBox_2)
        self.input_point.setGeometry(QtCore.QRect(20, 150, 201, 34))
        self.input_point.setObjectName("input_point")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 120, 241, 29))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_9.addWidget(self.label_5)
        self.input2_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input2_2.setObjectName("input2_2")
        self.horizontalLayout_9.addWidget(self.input2_2)
        self.input2_4 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input2_4.setObjectName("input2_4")
        self.horizontalLayout_9.addWidget(self.input2_4)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        self.input2_3 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input2_3.setObjectName("input2_3")
        self.horizontalLayout_8.addWidget(self.input2_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(9, 89, 241, 29))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.input1_1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input1_1.setObjectName("input1_1")
        self.horizontalLayout_5.addWidget(self.input1_1)
        self.input1_4 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input1_4.setObjectName("input1_4")
        self.horizontalLayout_5.addWidget(self.input1_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.input1_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input1_3.setObjectName("input1_3")
        self.horizontalLayout_7.addWidget(self.input1_3)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(270, 220, 551, 301))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(20, 30, 501, 241))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.point1_1 = QtWidgets.QLabel(self.widget)
        self.point1_1.setToolTip("")
        self.point1_1.setObjectName("point1_1")
        self.horizontalLayout.addWidget(self.point1_1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.point1_2 = QtWidgets.QLabel(self.widget)
        self.point1_2.setToolTip("")
        self.point1_2.setObjectName("point1_2")
        self.horizontalLayout_3.addWidget(self.point1_2)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.loc_point = QtWidgets.QLabel(self.widget)
        self.loc_point.setObjectName("loc_point")
        self.horizontalLayout_6.addWidget(self.loc_point)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_6.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.point2_1 = QtWidgets.QLabel(self.widget)
        self.point2_1.setToolTip("")
        self.point2_1.setObjectName("point2_1")
        self.horizontalLayout_10.addWidget(self.point2_1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_10.addWidget(self.lineEdit_3)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.point2_2 = QtWidgets.QLabel(self.widget)
        self.point2_2.setToolTip("")
        self.point2_2.setObjectName("point2_2")
        self.horizontalLayout_2.addWidget(self.point2_2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(280, 70, 511, 141))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.send_text = QtWidgets.QLineEdit(self.centralwidget)
        self.send_text.setGeometry(QtCore.QRect(280, 30, 281, 31))
        self.send_text.setObjectName("send_text")
        self.send_button = QtWidgets.QPushButton(self.centralwidget)
        self.send_button.setGeometry(QtCore.QRect(590, 30, 201, 34))
        self.send_button.setToolTip("")
        self.send_button.setObjectName("send_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.com_Port, self.com_Baud)
        MainWindow.setTabOrder(self.com_Baud, self.Connect_Button)
        MainWindow.setTabOrder(self.Connect_Button, self.plainTextEdit)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.Connect_Button.setText(_translate("MainWindow", "连接"))
        self.label.setText(_translate("MainWindow", "端口号："))
        self.label_2.setText(_translate("MainWindow", "波特率："))
        self.groupBox_2.setTitle(_translate("MainWindow", "单步测试"))
        self.Find_Button.setText(_translate("MainWindow", "查找"))
        self.Move_Button.setText(_translate("MainWindow", "移动"))
        self.input_point.setText(_translate("MainWindow", "输入坐标点"))
        self.label_5.setText(_translate("MainWindow", "点2："))
        self.label_3.setText(_translate("MainWindow", "点1："))
        self.groupBox_3.setTitle(_translate("MainWindow", "坐标"))
        self.point1_1.setText(_translate("MainWindow", "point1_1："))
        self.point1_2.setText(_translate("MainWindow", "point1_2："))
        self.loc_point.setText(_translate("MainWindow", "全站仪位置："))
        self.point2_1.setText(_translate("MainWindow", "point2_1："))
        self.point2_2.setText(_translate("MainWindow", "point2_2："))
        self.send_button.setText(_translate("MainWindow", "发送"))

